#!/bin/bash

CLIENT="mysql"
CLIENT_USER="root"
CLIENT_IP="127.0.0.1"
CLIENT_PORT="3306"
CLIENT_PWD="123456"
CLIENT_DB="asicme_test"
LOAD_FILE=$1
INTO_TABLE="user"

${CLIENT} -u${CLIENT_USER} -h${CLIENT_IP} -P${CLIENT_PORT} -p${CLIENT_PWD} ${CLIENT_DB} -Bqe "LOAD DATA INFILE '${LOAD_FILE}' INTO TABLE ${INTO_TABLE}
CHARACTER SET utf8
FIELDS TERMINATED BY '\t'">>tmp.log 
